name: Poker Lobby Parallel Tests

on: [push]

jobs:
  machine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Adding env variables
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: running only the table preview test
        uses: actions/checkout@v3
        with:
          working-directory: cypress/e2e/Poker
          spec: cypress/e2e/Poker/tablePreviewWithEmptySeats.cy.js

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
